[package]
name = "custom_qemu_emulator"
version = "0.1.0"
edition = "2021"

[lib]
name = "custom_qemu_emulator"
path = "src/lib.rs"

[[bin]]
name = "custom_qemu_emulator"
path = "src/main.rs"

[dependencies]
